### ISSUE TITLE
Build issue on my Pi 5 'error: too many arguments to function ‘xsk_buff_dma_sync_for_cpu’'

### ISSUE THREAD

**Issue by geerlingguy** [Time-Appliances-Project/TimeHAT#2]
Here's the full log output:

```
pi@time-pi:~/intel-igc-ppsfix $ sudo dkms build --force igc -v 5.4.0-7642.46
Sign command: /lib/modules/6.12.62+rpt-rpi-2712/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/igc/5.4.0-7642.46/source/dkms.conf)

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.12.62+rpt-rpi-2712 -C /lib/modules/6.12.62+rpt-rpi-2712/build M=/var/lib/dkms/igc/5.4.0-7642.46/build/src modules....(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.12.62+rpt-rpi-2712 (aarch64)
Consult /var/lib/dkms/igc/5.4.0-7642.46/build/make.log for more information.
pi@time-pi:~/intel-igc-ppsfix $ cat /var/lib/dkms/igc/5.4.0-7642.46/build/make.log
DKMS make.log for igc-5.4.0-7642.46 for kernel 6.12.62+rpt-rpi-2712 (aarch64)
Wed 25 Feb 10:33:04 CST 2026
make: Entering directory '/usr/src/linux-headers-6.12.62+rpt-rpi-2712'
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.o
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_mac.o
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_i225.o
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_base.o
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_nvm.o
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_phy.o
  CC [M]  /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_diag.o
/var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.c: In function ‘igc_construct_skb_zc’:
/var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.c:2713:15: error: implicit declaration of function ‘__napi_alloc_skb’; did you mean ‘napi_alloc_skb’? [-Werror=implicit-function-declaration]
 2713 |         skb = __napi_alloc_skb(&ring->q_vector->napi, totalsize,
      |               ^~~~~~~~~~~~~~~~
      |               napi_alloc_skb
/var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.c:2713:13: warning: assignment to ‘struct sk_buff *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2713 |         skb = __napi_alloc_skb(&ring->q_vector->napi, totalsize,
      |             ^
/var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.c: In function ‘igc_clean_rx_irq_zc’:
/var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.c:2816:17: error: too many arguments to function ‘xsk_buff_dma_sync_for_cpu’
 2816 |                 xsk_buff_dma_sync_for_cpu(bi->xdp, ring->xsk_pool);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.c:13:
/usr/src/linux-headers-6.12.62+rpt-common-rpi/include/net/xdp_sock_drv.h:402:20: note: declared here
  402 | static inline void xsk_buff_dma_sync_for_cpu(struct xdp_buff *xdp)
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.12.62+rpt-common-rpi/scripts/Makefile.build:249: /var/lib/dkms/igc/5.4.0-7642.46/build/src/igc_main.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.12.62+rpt-common-rpi/Makefile:1970: /var/lib/dkms/igc/5.4.0-7642.46/build/src] Error 2
make: *** [/usr/src/linux-headers-6.12.62+rpt-common-rpi/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.62+rpt-rpi-2712'
```

**Comment by geerlingguy** [comment]
Kernel:

```
pi@time-pi:~ $ uname -a
Linux time-pi 6.12.62+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.12.62-1+rpt1~bookworm (2026-01-19) aarch64 GNU/Linux
```

**Comment by JulianStj** [comment]
Added a new zip file for latest kernel, after doing full-upgrade on my rpi5 and using latest code, it all works. Please confirm before closing.

**Comment by geerlingguy** [comment]
Testing the newer version now:

```
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo dkms add .
Deprecated feature: REMAKE_INITRD (/home/pi/intel-igc-ppsfix_6_12/dkms.conf)
Deprecated feature: REMAKE_INITRD (/usr/src/igc-6.12.0-ppsfix.1/dkms.conf)
Creating symlink /var/lib/dkms/igc/6.12.0-ppsfix.1/source -> /usr/src/igc-6.12.0-ppsfix.1
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo dkms build --force igc -v 6.12.0-ppsfix.1
Sign command: /lib/modules/6.12.62+rpt-rpi-2712/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/igc/6.12.0-ppsfix.1/source/dkms.conf)

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.12.62+rpt-rpi-2712 -C /lib/modules/6.12.62+rpt-rpi-2712/build M=/var/lib/dkms/igc/6.12.0-ppsfix.1/build/src modules.....
Signing module /var/lib/dkms/igc/6.12.0-ppsfix.1/build/src/igc.ko
Cleaning build area...
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo dkms install --force igc -v 6.12.0-ppsfix.1
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/igc/6.12.0-ppsfix.1/source/dkms.conf)

igc.ko.xz:
Running module version sanity check.
 - Original module
 - Installation
   - Installing to /lib/modules/6.12.62+rpt-rpi-2712/updates/dkms/
depmod...
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo cp /lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/igc/igc.ko.xz \
        /lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/igc/igc.ko.xz.bak
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo cp /lib/modules/$(uname -r)/updates/dkms/igc.ko.xz \
        /lib/modules/$(uname -r)/kernel/drivers/net/ethernet/intel/igc/igc.ko.xz
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo depmod -a
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo update-initramfs -u -k $(uname -r)
update-initramfs: Generating /boot/initrd.img-6.12.62+rpt-rpi-2712
'/boot/initrd.img-6.12.62+rpt-rpi-2712' -> '/boot/firmware/initramfs_2712'
pi@time-pi:~/intel-igc-ppsfix_6_12 $ sudo reboot
```

After reboot:

```
pi@time-pi:~ $ modinfo igc | grep filename
filename:       /lib/modules/6.12.62+rpt-rpi-2712/updates/dkms/igc.ko.xz
pi@time-pi:~ $ ethtool -i eth1
driver: igc
version: 6.12.62+rpt-rpi-2712
firmware-version: 2014:8877
expansion-rom-version: 
bus-info: 0001:01:00.0
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```

Question: when verifying PPS, do I need to measure the output with an oscilloscope? And which SMA jack should I use?

```
# Read 5 external timestamps (should show ~1.000000000s intervals)
sudo testptp -d /dev/ptp0 -e 5
```

**Comment by geerlingguy** [comment]
Separate question: are the changes in `igc` upstreamed or have any potential of hitting mainline Linux at some point?

Also, do you have the actual patch file you're applying somewhere? Maybe we could use GitHub Actions to automatically build/zip new dkim versions?

**Comment by JulianStj** [comment]
You can measure PPS with an oscilloscope, but it will always look like 1PPS with or without this patch. To verify it with an oscilloscope, you'll need either a GPS 1PPS or another device with GPS locked 1PPS. The SMA port closer to the 40-pin connector is PPS output.

For upstreaming, that's outside my purview at the moment. If anybody has a contact or path for that, it'd be great.

I don't have a patch , just the files here. Shouldn't be too hard to make the patch, just grab the igc directory from the kernel matching this version and diff everything.

Will leave this issue open for further verification, thanks!

**Comment by geerlingguy** [comment]
> You can measure PPS with an oscilloscope, but it will always look like 1PPS with or without this patch. To verify it with an oscilloscope, you'll need either a GPS 1PPS or another device with GPS locked 1PPS. The SMA port closer to the 40-pin connector is PPS output.

Okay, so for the verification I should have:

  - Channel 1 getting PPS out of separate GPS
  - Channel 2 getting PPS out of TimeHAT SMA plug nearest 40 pin header

Then I just confirm I'm getting rising edges within a few ns of each other? (Do you know about how accurate it should be, assuming everything's working, and I have a really good external reference?)

**Comment by JulianStj** [comment]
That's the easiest way of verifying yeah, after setting up ts2phc running and gps is locked on the TimeHAT.

Depending how good the GPS lock and GPS modules are, probably within 50-100 nanoseconds is to be expected, depending how long of a time window you look at for the min-max variation.

**Comment by folkertvanheusden** [comment]
> You can measure PPS with an oscilloscope, but it will always look like 1PPS with or without this patch. To verify it with an oscilloscope, you'll need either a GPS 1PPS or another device with GPS locked 1PPS. The SMA port closer to the 40-pin connector is PPS output.

Can you provide a full list of details maybe somewhere? Maybe include schematics?
For example: which SMA maps to what in the Linux operating system and how to configure them. Please keep in mind that not all setups use a GPS in the provided m2 slot.

**Comment by TimeAppliancesStore** [comment]
The SMA port closer to the 40 pin connector is buffered SDP0 from the I226, intended for PPS output generated by configuring the I226 with testptp as listed on the store pages.

The other SMA port is buffered SDP1 to the I226, intended for timestamp or 1PPS input, and can be used to discipline the I226 with ts2phc or to read the timestamps with testptp.
